services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - demo-server

  demo-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
